# Generated by Django 2.2.4 on 2019-08-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('des', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
    ]
