# Generated by Django 2.2.4 on 2019-10-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='w_type',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
